// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDotU4uCj58Yulas6H4G6f3_lhmm3k_N9k',
    appId: '1:1047336153858:web:e0ee923eecd26c6810c81b',
    messagingSenderId: '1047336153858',
    projectId: 'habittry-2026',
    authDomain: 'habittry-2026.firebaseapp.com',
    storageBucket: 'habittry-2026.firebasestorage.app',
    measurementId: 'G-GB4F404WNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLsag9B7B6Ryo_qK4EpIh6yEDSW8MtWeI',
    appId: '1:1047336153858:android:e86ee22ca8f9dc4910c81b',
    messagingSenderId: '1047336153858',
    projectId: 'habittry-2026',
    storageBucket: 'habittry-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOdKWt14SNhqohmAtJ-O2Tlq-H5DFhMng',
    appId: '1:1047336153858:ios:7141c8b7fbe54e9910c81b',
    messagingSenderId: '1047336153858',
    projectId: 'habittry-2026',
    storageBucket: 'habittry-2026.firebasestorage.app',
    iosBundleId: 'com.example.habittry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOdKWt14SNhqohmAtJ-O2Tlq-H5DFhMng',
    appId: '1:1047336153858:ios:7141c8b7fbe54e9910c81b',
    messagingSenderId: '1047336153858',
    projectId: 'habittry-2026',
    storageBucket: 'habittry-2026.firebasestorage.app',
    iosBundleId: 'com.example.habittry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDotU4uCj58Yulas6H4G6f3_lhmm3k_N9k',
    appId: '1:1047336153858:web:7621cf000ba57c5010c81b',
    messagingSenderId: '1047336153858',
    projectId: 'habittry-2026',
    authDomain: 'habittry-2026.firebaseapp.com',
    storageBucket: 'habittry-2026.firebasestorage.app',
    measurementId: 'G-65C0KMNY66',
  );

}